### ISSUE TITLE
Concerning the executable file

### ISSUE THREAD

**Issue by ModarHalimeh** [adamjgnoel/AcCoRD#41]
Hey Adam.
I was reviewing the latest update 0.4.1.1 and noticed the pre-compiled binary accord_win.exe is gone. 
I know I can build it using the provided source codes using any compiler
but then that means the Readme file needs to be edited to remove the part where it's mentioned to use the pre compiled executable.
if that's not intended, I guess you need to add the pre-compiled file :)

Best Regards,

**Comment by adamjgnoel** [comment]
The pre-compiled executables are available on the "releases" page. It made more sense to have them there rather than update all of them every time the code changes.

You're right though that the location is not specified in the README. It is on the wiki, though. I can add the link to the releases page in the README.

**Comment by ModarHalimeh** [comment]
Oh you are right. 
Sorry I didn't notice that "I usually read the Text file itself, I should've paid more attention to the Wiki page".

:)

**Comment by adamjgnoel** [comment]
No problem. Thanks for spotting the ambiguity in the readme

**Comment by adamjgnoel** [comment]
Readme updated to reflect where to find executables.
